src/Entity/Job.php
<?php

namespace App\Entity;

use App\Repository\JobRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\Image;
/**
 * @ORM\Entity(repositoryClass=JobRepository::class)
 */
class Job
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $company;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $expires_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;
    /**
* @ORM\OneToOne(targetEntity="Image",cascade={"persist"})
* @ORM\JoinColumn(nullable=true)
*/
private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->company;
    }

    public function setCompany(string $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getExpiresAt(): ?\DateTimeImmutable
    {
        return $this->expires_at;
    }

    public function setExpiresAt(\DateTimeImmutable $expires_at): self
    {
        $this->expires_at = $expires_at;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getImage(): ?Image
    {
        return $this->image;
    }

    public function setImage(?Image $image): self
    {
        $this->image = $image;

        return $this;
    }
}

src/Form/JobType.php
<?php

namespace App\Form;

use App\Entity\Job;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
class JobType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('type')
            ->add('company')
            ->add('description')
            ->add('expires_at')
            ->add('email')
            ->add('Valider',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Job::class,
        ]);
    }
}

src/Controller/JobController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Job;
use App\Entity\Image;
use App\Entity\Candidature;
class JobController extends AbstractController
{
    /**
     * @Route("/job", name="app_job")
     */
    public function index(): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $job = new Job();
        $job->setType('Architecte');
        $job->setCompany('OffShoreBox');
        $job->setDescription('Genie logiciel ');
        $job->setExpiresAt(new \DateTimeImmutable());
        $job->setEmail('haykel@gmail.com');
        $image=new Image();
        $image->setUrl('https://cdn.pixabay.com/photo/2015/10/30/10/03/gold-1013618_960_720.jpg');
        $image->setAlt('Job de rêves');
        $job->setImage($image);
        $candidature1=new Candidature();
        $candidature1->setCandidat("Rhaiem");
        $candidature1->setContenu("formation J2EE");
        $candidature1->setDatec(new \DateTime());
        $candidature2=new Candidature();
        $candidature2->setCandidat("Salima");
        $candidature2->setContenu("formation Symfony");
        $candidature2->setDatec(new \DateTime());
        $candidature1->setJob($job);
        $candidature2->setJob($job);
        $entityManager->persist($job);
        $entityManager->persist($candidature1);
        $entityManager->persist($candidature2);
        $entityManager->flush();
        return $this->render('job/index.html.twig', [
            'id' =>$job->getId(),
        ]);
    }
    /**
* @Route("/job/{id}", name="job_show")
*/
public function show($id)
{
    $job = $this->getDoctrine()
    ->getRepository(Job::class)
    ->find($id);

$em=$this->getDoctrine()->getManager();
$listCandidatures=$em->getRepository(Candidature::class)
    ->findBy(['Job'=>$job]);

if (!$job) {
    throw $this->createNotFoundException(
        'No job found for id '.$id
    );
}
return $this->render('job/show.html.twig', [
    'listCandidatures'=> $listCandidatures,
    'job' =>$job

]);
 }
/**
     * @Route("/ajout", name="Ajouter")
     */
    public function ajouter_cand(Request $request)
    {
        $candidat = new Candidature();
        $fb = $this->createFormBuilder($candidat)
            ->add('candidat', TextType::class)
            ->add('contenu', TextType::class, array("label" => "Contenu"))
            ->add('datec', DateType::class)
            ->add('job', EntityType::class, [
                'class' => Job::class,
                'choice_label' => 'type',
            ])
            ->add('Valider', SubmitType::class);
        $form = $fb->getForm();
        //injection dans la base de données
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($candidat);
            $em->flush();
            return $this->redirectToRoute('home');
        }
        return $this->render('job/ajouter.html.twig',
            ['f' => $form->createView()]);
    }
    /**
    * @Route ("/",name="home")
    */
   public function  home(){
    $em = $this->getDoctrine()->getManager();
    $repo = $em->getRepository(Candidature::class);
    $lesCandidats = $repo->findAll();
    return $this->render('job/home.html.twig',
    [ 'lesCandidats' => $lesCandidats ]);
   }
 /**
     *
     * @Route("/add",name="ajout_job")
     */
    public function ajouter2(Request $request)
    {
       
        $job = new Job();
        $form = $this->createForm("App\Form\JobType",$job);
        $form -> handleRequest($request);
        if ($form->isSubmitted())
        {
            $em = $this->getDoctrine()->getManager();
            $em->persist($job);
            $em->flush();
            return $this->redirectToRoute('home');
        }

        return $this->render('job/ajouter.html.twig',
            ['f'=>$form->createView()]);
    }
     /**
     * @Route("/editU/{id}", name="edit_user")
     * Method({"GET","POST"})
     */
    public function edit(Request $request, $id)
    {   $candidat = new Candidature();
        $candidat = $this->getDoctrine()
            ->getRepository(Candidature::class)
            ->find($id);

        if (!$candidat) {
            throw $this->createNotFoundException(
                'No candidat found for id '.$id
            );
        }
        $fb = $this->createFormBuilder($candidat)

            ->add('candidat', TextType::class)
            ->add('contenu', TextType::class, array("label" => "Contenu"))
            ->add('datec', DateType::class)
            ->add('job', EntityType::class, [
                'class' => Job::class,
                'choice_label' => 'type',
            ])
            ->add('Valider', SubmitType::class);
        // générer le formulaire à partir du FormBuilder
        $form = $fb->getForm();
        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();
            return $this->redirectToRoute('home');
        }
        return $this->render('job/ajouter.html.twig',
            ['f' => $form->createView()] );
    }
    /**
     * @Route("/supp/{id}", name="cand_delete")
     */
    public function delete(Request $request, $id): Response
    {
        $c = $this->getDoctrine()
            ->getRepository(Candidature::class)
            ->find($id);
        if (!$c) {
            throw $this->createNotFoundException(
                'No job found for id '.$id
            );
        }
        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($c);

        $entityManager->flush();
        return $this->redirectToRoute('home');
    }
  /**
    * @Route ("/liste",name="liste_job")
    */
    public function  liste(){
        $em = $this->getDoctrine()->getManager();
        $repo = $em->getRepository(Job::class);
        $lesJobs = $repo->findAll();
        return $this->render('job/liste.html.twig',
        [ 'lesJobs' => $lesJobs ]);
       }
}

templates/job/ajouter.html.twig
{% extends 'base.html.twig' %}
{% block title %}Ajout Nouvel Enregistrement{% endblock %}
{% block body %}
    {% block titre %}{{parent()|upper}} - Ajout Nouvel Enregistrement  {% endblock %}
    <h2> Ajouter </h2>
    {{ form_start(f) }}
    {{ form_widget(f) }}
    {{ form_end (f)}}
{% endblock %}

templates/job/home.html.twig
{% extends 'base.html.twig' %}
{% block body %}
   
  <h2>Liste des Candidats | <small>
   <a href="{{ path('Ajouter') }}">Ajouter</a> </small></h2>
    {% for msg in app.flashes('notice') %}
        {{ msg }}
    {% endfor %}
   <table class="table table-hover table-striped" border="1">
    <thead>
    <tr>
      <th>#</th>
      <th>Nom & Prenom</th>
      <th>Contenu</th>
      <th>Date</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    {% for candidat in lesCandidats %}
      <tr>
        <td>{{ candidat.id }}</td>
        <td>{{ candidat.candidat | upper}} </td>
        <td>{{ candidat.datec | date('d/m/yy')}} </td>
        <td>{{ candidat.contenu }}</td>
        <td>
          <a class="btn btn-primary" href="{{ path('job_show', {'id':candidat.id }) }}">voir</a>
          <a class="btn btn-info" href="{{ path('edit_user', {'id':candidat.id }) }}">Modifier</a>
           <a class="btn btn-danger" href="{{ path('cand_delete', {'id':candidat.id }) }}" onclick="return confirm('Are you sure to delete!{{ candidat.candidat }}')">Supprimer</a>
        </td>
      </tr>
    {% else %}
      <tr>
        <td colspan="5" >Aucun abonneé</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/job/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello JobController!{% endblock %}

{% block body %}

<div class="example-wrapper">
   <h1>Ajout avec succès job num {{id}} </h1>
  
</div>
{% endblock %}

templates/job/liste.html.twig
{% extends 'base.html.twig' %}
{% block body %}
   
  <h2>Liste des Candidats | <small>
   <a href="{{ path('ajout_job') }}">Ajouter</a> </small></h2>
    {% for msg in app.flashes('notice') %}
        {{ msg }}
    {% endfor %}
   <table class="table table-hover table-striped" border="1">
    <thead>
    <tr>
      <th>#</th>
      <th>Type</th>
      <th>company</th>
      <th>Date expiration</th>
      <th>Description</th>
    </tr>
    </thead>
    <tbody>
    {% for emp in lesJobs %}
      <tr>
        <td>{{ emp.id }}</td>
        <td>{{ emp.type | upper}} </td>
        <td>{{ emp.getExpiresAt() | date('d/m/yy')}} </td>
        <td>{{ emp.description }}</td>
        <td>
          <a class="btn btn-primary" href="#">voir</a>
          <a class="btn btn-info" href="#">Modifier</a>
           <a class="btn btn-danger">Supprimer</a>
        </td>
      </tr>
  
    {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/job/show.html.twig
{% extends "base.html.twig" %}
{% block title %}{{parent()}} - Edit{% endblock %}
{% block titre %}{{parent()|upper}} - Consultation de {{ job.getType() }} {% endblock %}
{% block body %}
<h1>projet : {{job.type}}</h1>
    <h3>entreprise {{job.Company}} </h3><br>
    <h3>{{ job.Description }}</h3>
    <h3>Date d'expiration :{{ job.expiresAt| date('d-m-Y')}}</h3>
    <h3>Candidatures</h3>
    <ul class="nav nav-pills nav-stacked">
        {% for candidature in listCandidatures %}
            <h4> Candidat </h4><br>
            <li>{{ candidature.candidat}}</li>
            <li>{{ candidature.contenu}}</li>
            <li>{{ candidature.datec | date('d-m-Y')}}</li>

            <li>=====================================</li>
        {% endfor %}
    </ul>
{% endblock %}